<a href="https://colab.research.google.com/github/sandamali-2002/sandamali-2002-Conversational-RAG-Application-with-LangChain-and-OpenAI-LLM.ipynb/blob/main/keyword_and_semantic_search.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy scikit-learn sentence-transformers -q

In [2]:
documents = [
    "The T20 World Cup 2024 is in full swing, bringing excitement and drama to cricket fans worldwide.India's team, captained by Rohit Sharma, is preparing for a crucial match against Ireland, with standout player Jasprit Bumrah expected to play a pivotal role in their campaign.The tournament has already seen controversy, particularly concerning the pitch conditions at Nassau County International Cricket Stadium in New York, which came under fire after a low-scoring game between Sri Lanka and South Africa.",
    "The world of football is buzzing with excitement as major tournaments and league matches continue to captivate fans globally.In the UEFA Champions League, the semi-final matchups have been set, with defending champions Real Madrid set to face Manchester City, while Bayern Munich will take on Paris Saint-Germain.Both ties promise thrilling encounters, featuring some of the best talents in world football.",
    "As election season heats up, the latest developments reveal a highly competitive atmosphere across several key races.The presidential election has seen intense campaigning from all major candidates, with recent polls indicating a tight race.Incumbent President Jane Doe is seeking re-election on a platform of economic stability and healthcare reform, while her main rival, Senator John Smith, focuses on education and climate change initiatives.",
    "The AI revolution continues to transform industries and reshape the global economy.Significant advancements in artificial intelligence have led to breakthroughs in healthcare, with AI-driven diagnostics improving patient outcomes and reducing costs.Autonomous systems are becoming increasingly prevalent in logistics and transportation, enhancing efficiency and safety."
]

In [3]:
import re

def preprocessing(text):
  text=text.lower()
  text=re.sub(r'[^\w\s]','',text)
  return text
preprocessed_documents=[preprocessing(doc) for doc in documents]

for doc in preprocessed_documents:
  print(doc)




the t20 world cup 2024 is in full swing bringing excitement and drama to cricket fans worldwideindias team captained by rohit sharma is preparing for a crucial match against ireland with standout player jasprit bumrah expected to play a pivotal role in their campaignthe tournament has already seen controversy particularly concerning the pitch conditions at nassau county international cricket stadium in new york which came under fire after a lowscoring game between sri lanka and south africa
the world of football is buzzing with excitement as major tournaments and league matches continue to captivate fans globallyin the uefa champions league the semifinal matchups have been set with defending champions real madrid set to face manchester city while bayern munich will take on paris saintgermainboth ties promise thrilling encounters featuring some of the best talents in world football
as election season heats up the latest developments reveal a highly competitive atmosphere across several 

Keyword Search

In [4]:
test_query = "machine learning is a subset of artificial intelligence"

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [6]:
vectorizer=TfidfVectorizer()

In [7]:
spars_vectors=vectorizer.fit_transform(preprocessed_documents)

In [8]:
len(spars_vectors.toarray()[0])

183

In [9]:
spars_vectors.toarray()[0]

array([0.11827505, 0.        , 0.        , 0.11827505, 0.11827505,
       0.11827505, 0.        , 0.        , 0.        , 0.11827505,
       0.12344165, 0.        , 0.        , 0.        , 0.11827505,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.11827505, 0.        , 0.11827505, 0.11827505, 0.        ,
       0.11827505, 0.11827505, 0.        , 0.11827505, 0.        ,
       0.11827505, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.11827505, 0.11827505, 0.        ,
       0.        , 0.11827505, 0.        , 0.11827505, 0.23655009,
       0.11827505, 0.11827505, 0.        , 0.        , 0.        ,
       0.        , 0.11827505, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.09324941,
       0.11827505, 0.        , 0.09324941, 0.        , 0.11827505,
       0.        , 0.        , 0.11827505, 0.        , 0.11827505,
       0.11827505, 0.        , 0.        , 0.09324941, 0.     

In [10]:
test_query_sparse_vector = vectorizer.transform([test_query])

In [11]:
test_query_sparse_vector.toarray()[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.57457953, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [12]:
len(test_query_sparse_vector.toarray()[0])

183

In [13]:
keyword_similarities=cosine_similarity(spars_vectors,test_query_sparse_vector)
keyword_similarities

array([[0.05537393],
       [0.11902777],
       [0.07839555],
       [0.17677653]])

In [14]:
ranked_index=np.argsort(keyword_similarities,axis=0)[::-1]
ranked_index

array([[3],
       [1],
       [2],
       [0]])

In [16]:
ranked_documents=[documents[i] for i in ranked_index]

for doc in ranked_documents:
    print(doc)



TypeError: only integer scalar arrays can be converted to a scalar index

SEmentic search

In [17]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
from sentence_transformers import SentenceTransformer

In [18]:
edding_model=SentenceTransformer('all-MiniLM-L6-v2')

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  | 
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [19]:
dense_vectors=edding_model.encode(preprocessed_documents)

In [20]:
len(dense_vectors[0])

384

In [23]:
dense_vectors[0]

array([ 3.78725417e-02,  6.28795922e-02,  4.96302918e-02, -4.81413789e-02,
        2.34321933e-02,  2.53333412e-02, -1.57561041e-02,  8.40461627e-03,
        5.60538881e-02,  1.09072074e-01, -7.29954168e-02, -6.40174001e-02,
        6.67362511e-02,  1.04443640e-01,  4.70714532e-02, -4.18378226e-02,
       -3.28989956e-03, -1.57375962e-01, -1.53392116e-02, -1.17675208e-01,
        4.59880531e-02,  2.67154649e-02, -6.25342131e-02, -2.50020940e-02,
       -4.53811698e-02, -7.85905868e-02,  3.79795209e-02, -5.51528856e-03,
       -4.80996594e-02,  5.81194088e-02,  6.05508685e-02,  4.77277264e-02,
       -2.52205562e-02,  2.77488958e-02, -6.69680610e-02, -7.10612014e-02,
       -5.36492802e-02,  9.40861627e-02,  8.91835764e-02,  2.59057079e-02,
       -7.98968226e-03, -1.13937482e-01, -1.13619687e-02, -2.77683809e-02,
        9.26760808e-02,  1.55693619e-02,  1.12218242e-02, -3.00633647e-02,
       -3.41817699e-02,  1.04039051e-02,  7.66977062e-03, -2.35977545e-02,
        6.10016249e-02, -

In [24]:
test_quary_dense_vector=edding_model.encode([test_query])

In [26]:
len(test_query[0])

1

In [27]:
sementic_similaraties=cosine_similarity(dense_vectors,test_quary_dense_vector)
sementic_similaraties

array([[0.01992228],
       [0.09100749],
       [0.04911967],
       [0.37954292]], dtype=float32)

In [28]:
ranked_indexing=np.argsort(sementic_similaraties,axis=0)[::-1].flatten()
ranked_index

array([[3],
       [1],
       [2],
       [0]])